version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/apache/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: cajero2
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tienda
      MYSQL_PASSWORD: tienda123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/tienda.sql:/docker-entrypoint-initdb.d/tienda.sql

volumes:
  db_data:
